"""Add appointments table

Revision ID: 25ead5c5320c
Revises: 
Create Date: 2025-09-30 16:52:11.534832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ead5c5320c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('patient_email', sa.String(length=100), nullable=False),
    sa.Column('patient_phone', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('known_allergies', sa.Text(), nullable=True),
    sa.Column('current_medication', sa.Text(), nullable=True),
    sa.Column('medical_history', sa.Text(), nullable=True),
    sa.Column('preferred_doctor', sa.String(length=100), nullable=True),
    sa.Column('additional_note', sa.Text(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('appointment_time', sa.DateTime(), nullable=False),
    sa.Column('google_calendar_event_id', sa.String(length=100), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_appointment')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index('idx_appointment_id', ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index('idx_appointment_id')

    op.drop_table('appointments')
    # ### end Alembic commands ###
